#include "../common/real_test_gateway.hpp"
#include "../../runtime/agent/ollama_model_provider.hpp"
#include "../../runtime/agent/plan_validator.hpp"
#include <iostream>
#include <cassert>

using namespace vani::contracts;
using namespace vani::runtime;
using namespace vani::runtime::agent;

int main() {
    std::cout << std::unitbuf;
    std::cerr << std::unitbuf;
    std::cout << "=== RUNNING TEST: test_phase7b_real_replanning ===\n";

    auto model_provider = std::make_shared<OllamaAgentModelProvider>("qwen2.5:3b");
    if (!model_provider->ping()) model_provider->set_model_name("llama3.2:1b");
    if (!model_provider->ping()) {
        std::cerr << "[BLOCKED] Local Ollama service is not reachable on 127.0.0.1:11434\n";
        return 1;
    }

    AgentRequest req;
    req.request_id = "req_replan_real";
    req.goal = "Launch custom editor tool or fallback to notepad";

    auto memory = std::make_shared<ShortTermTaskMemory>();
    auto plan1_res = model_provider->generate_plan(req, memory);
    if (!plan1_res.is_ok()) {
        std::cerr << "FAIL: Initial plan generation failed: " << plan1_res.error().message << "\n";
        return 1;
    }

    auto tel1 = model_provider->last_telemetry();
    std::cout << "--> Initial Plan Generated by Real LLM (Tokens: " << tel1.output_token_count << ")\n";

    // Simulate an environmental failure observation
    AgentPlan plan1 = plan1_res.value();
    std::string failed_step = plan1.steps.empty() ? "step_1" : plan1.steps[0].step_id;

    AgentObservation fail_obs;
    fail_obs.step_id = failed_step;
    fail_obs.success = false;
    fail_obs.error = "Primary editor executable not found in PATH: 'custom_editor.exe'";

    std::cout << "--> Triggering Real LLM Dynamic Replan with failure observation\n";
    auto plan2_res = model_provider->replan(req, plan1, failed_step, fail_obs, memory);
    if (!plan2_res.is_ok()) {
        std::cerr << "FAIL: Replan failed: " << plan2_res.error().message << "\n";
        return 1;
    }

    auto tel2 = model_provider->last_telemetry();
    std::cout << "--> Recovery Plan B Generated by Real LLM (Tokens: " << tel2.output_token_count << ", Latency: " << tel2.latency_ms << " ms)\n";

    if (tel2.output_token_count == 0) {
        std::cerr << "FAIL: Output token count was 0\n";
        return 1;
    }

    // Validate Plan B using PlanValidator
    PlanValidator validator;
    AgentResourceBudget budget;
    auto val_res = validator.validate_plan(plan2_res.value(), budget);
    if (!val_res.is_valid) {
        std::cerr << "FAIL: Plan B validation failed: " << val_res.error_message << "\n";
        return 1;
    }

    std::cout << "[PASS] REAL_MODEL_REPLANNING = TRUE\n";
    return 0;
}
